### ISSUE TITLE
dealing with innaccessible GitHub tags

### ISSUE THREAD

**Issue by randomicecube** [chains-project/dirty-waters#38]
Specifically for Maven, there are many instances of "poorly named" GitHub tags which don't match the versions specified in pom files: as an example, most of them specify versions in the pom as `X.Y.Z`, but then in GitHub they're commonly `something-X.Y.Z`. I thought about checking if the version itself they give us is present, as a substring, in any of the GitHub tags, besides all the checks we already do for that, but I also thought this may not be very safe -- if a version is specified in the pom as `.`, for instance, this could lead to them pretty much always being found/accepted.
What do you think? cc @monperrus @Stamp9 

I'm leaving an example below which I got from spoon, but there are many more like this

![image](https://github.com/user-attachments/assets/b0502d30-d470-4aa5-8702-38aff4be2eb0)
![image](https://github.com/user-attachments/assets/7b0d2fcf-aa5a-4a4e-817c-ae92a9d0f5b7)

(BTW, I know that the `package_name` in the `tag_format` function currently doesn't really make sense when I'm passing it as maven packages, I'll fix it soon; the core problem here still applies, regardless)

**Comment by randomicecube** [comment]
> We can design and document a systematic solution to lookup tags

Well, there's already a beginning for that [here](https://github.com/chains-project/dirty-waters/blob/097111699fa615ebb03b51b56810309e4b92e2ee/tool/compare_commits.py#L14), which looks for

- `<tag>`
- `v<tag>`
- `<packagename>@<tag>`
- `<packagename>-v<tag>`
- `<packagename>-<tag>`

So, I guess the steps would be to build a systematic list of tag/version formats which we think would be extensive enough to look for, and assume that if it's not one of those, they either don't exist OR are poorly documented/named?

I think from the ones you mentioned, the only one missing is the second one (with a `_` separator). I'll implement that, and also try to think of some more tag formats which could be relevant. If you remember any other ones, please write them here too!

**Comment by monperrus** [comment]
> So, I guess the steps would be to build a systematic list of tag/version formats which we think would be extensive enough to look for, and assume that if it's not one of those, they either don't exist OR are poorly documented/named?

yes, exactly

**Comment by algomaster99** [comment]
@randomicecube checkout [Table 3 of AROMA paper](https://dl.acm.org/doi/pdf/10.1145/3643764).

**Comment by randomicecube** [comment]
Thank you @algomaster99 !

Re-opening the issue to take this table into account
