### ISSUE TITLE
push to Pypi with CD

### ISSUE THREAD

**Issue by monperrus** [chains-project/dirty-waters#6]
push to Pypi, with a CD script, for each commit

cc/ @randomicecube

**Comment by randomicecube** [comment]
@monperrus would it be for each commit, or for each tagged version?

**Comment by monperrus** [comment]
each commit.

**Comment by randomicecube** [comment]
Should we, then, tag each commit going onto main? Assuming that the development is fully PR-based, I guess that could make sense; otherwise, I'm not sure if it'd make sense to do this per main-commit, since pypi's (and other package managers) worked based exclusively on versions, right?

**Comment by monperrus** [comment]
> Should we, then, tag each commit going onto main?

why not. in git a tag and a commit are the same thing, a "git tree". Perhaps PyPi knows how to work commit based (I hope), if not we can hack one tag per commit.
